### ISSUE TITLE
Move status button from twtxt file to status page

### ISSUE THREAD

**Issue by alexwennerberg** [alexwennerberg/flounder#1]
Motivation: UX for adding statuses, while it makes very clear what's going on (you are writing to your twtxt file), is kind of clunky.

I want to move the "append status" textarea to the statuses page, change it to a form that submits a post request, and then append to the user's twtxt file (after doing some text processing, e.g. replacing @user tags)

**Comment by radio-alice** [comment]
yo it's zach from the mailing list– would this be a good one to start with?

**Comment by alexwennerberg** [comment]
Hey Zach! Go for it. Let me know if you have any questions about the build process. Feel free to add to the README, etc. I can email you my nginx configuration too

**Comment by radio-alice** [comment]
will do! Is the nginx config particularly complicated? I'm using caddy on my little server rn.

**Comment by radio-alice** [comment]
ok building spits out a bunch of x86 errors about missing assembly instructions and the "ring" dependency– have you gotten it to build on osx or will it only run on linux?

**Comment by alexwennerberg** [comment]
Ring issue might be https://github.com/briansmith/ring/issues/791

Followed up via email abt server config
