### ISSUE TITLE
UI - Text box hint for "Create file by name" is partially truncated

### ISSUE THREAD

**Issue by TactfulOgre** [alexwennerberg/flounder#20]
In the text box used for creating a new file, the hint text is partially truncated. The full unobstructed text of the hint is "New filename, e.g. newfile.gmi".

**Steps to reproduce:**

1. Log into Flounder
2. Proceed to *Manage Your Site*
3. View the text box below _Create file by name_
4. Notice that the hint in the text box is partially truncated

**Actual result:**
The text box hint for _Create file by name_ is partially truncated.

**Expected result:**
The text box hint for _Create file by name_ is fully readable.

**Notes:**
* Reproduction rate: 5/5
* The issue is confirmed to occur in Firefox, Chrome, and Microsoft Edge.
* Please refer to the attached image:
![20_A](https://user-images.githubusercontent.com/70036083/90930873-c8009800-e3fb-11ea-8538-2c90c691a170.jpg)

**Comment by alexwennerberg** [comment]
Fixed! Won't be deployed for a while though
